version: "0.1.0"
services:
  mongodb:
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - "27027:27017"

  cashflow-rest:
    build:
      context: .
      dockerfile: apps/cashflow-rest/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3001
    volumes:
      - ./:/root
    depends_on:
      - mongodb

volumes:
  mongodb:
